FROM docker.n8n.io/n8nio/n8n:latest

ENV N8N_PORT=10000
ENV N8N_PROTOCOL=http
ENV N8N_HOST=0.0.0.0
ENV N8N_EDITOR_ENABLED=true
ENV N8N_SECURE_COOKIE=false
ENV GENERIC_TIMEZONE=America/Los_Angeles
ENV TZ=America/Los_Angeles
ENV N8N_DIAGNOSTICS_ENABLED=false
ENV N8N_PERSONALIZATION_ENABLED=false

EXPOSE 10000

CMD ["n8n", "start"]
